print(77,88,99)
print(77,88,99,sep="$")
print(77,88,99,sep="$",end="")
print(1010)

print("I hate raining")
print("raining","sunny","snowy","windy")
print("raining","sunny","snowy","windy",sep="!")
print("raining","sunny","snowy","windy",sep="!",end="")
print("sniny")
