import turtle
t=turtle.Turtle()
t.pencolor("yellow")
t.pensize(5)
t.setheading(90)
angle=int(60)
t.right(angle)
length=int(150)
t.fillcolor("lightyellow")
t.begin_fill()
for i in range(5):
    t.forward(length)
    t.right(120)
    t.forward(length)
    t.left(60)
t.forward(length)
t.right(120)
t.forward(length)
t.end_fill()
