import turtle
import random
t=turtle.Turtle()
t.pensize(4)
t.speed(10000)
screen=turtle.Screen()
screen.bgcolor("black")
t.penup()
t.setheading(150)
t.forward(500)
t.pendown()
t.pencolor("yellow")
t.fillcolor("yellow")
for i in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()

t.penup()
t.setheading(0)
t.forward(600)
t.pencolor("lightyellow")
t.fillcolor("lightyellow")
for i in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()


t.penup()
t.setheading(250)
t.forward(500)
t.pendown()
t.pencolor("gold")
t.fillcolor("gold")
for i in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()

t.penup()
t.setheading(180)
t.forward(450)
t.pendown()
t.pencolor("lemonchiffon")
t.fillcolor("lemonchiffon")
for i in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()

t.penup()
t.setheading(0)
t.forward(200)
t.pendown()
t.pencolor("azure")
t.fillcolor("azure")
for h in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()


t.penup()
t.setheading(45)
t.forward(800)
t.pendown()
t.pencolor("yellow")
t.fillcolor("yellow")
for h in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()

t.penup()
t.setheading(270)
t.forward(700)
t.pendown()
t.pencolor("whitesmoke")
t.fillcolor("whitesmoke")
for i in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()

t.penup()
t.setheading(180)
t.forward(500)
t.pendown()
t.pencolor("khaki")
t.fillcolor("khaki")
for i in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()

t.penup()
t.setheading(90)
t.forward(720)
t.pendown()
t.pencolor("lavender")
t.fillcolor("lavender")
for i in range(5):
    t.begin_fill()
    t.forward(20)
    t.right(150)
    t.forward(20)
    t.left(75)
    t.end_fill()

t.penup()
t.setheading(270)
t.forward(100)
t.setheading(0)
t.forward(600)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
t.pencolor("yellow")
t.circle(50)
t.end_fill()




t.penup()
t.setheading(180)
t.forward(500)
t.setheading(270)
t.forward(150)
t.left(90)
t.right(240)
t.goto(-100,150)
t.pendown()
t.fillcolor("red")
t.begin_fill()
t.pencolor("crimson")
t.circle(50,180)
t.forward(70)
t.penup()
t.goto(-100,150)
t.left(70)
t.pendown()
t.circle(-50,180)
t.forward(70)
t.end_fill()




t.penup()
t.setheading(180)
t.forward(500)
t.setheading(270)
t.forward(150)
t.left(90)
t.right(240)
t.goto(-100,150)
t.pendown()
t.fillcolor("deeppink")
t.begin_fill()
t.pencolor("crimson")
t.circle(40,180)
t.forward(60)
t.penup()
t.goto(-100,150)
t.left(70)
t.pendown()
t.circle(-40,180)
t.forward(60)
t.end_fill()


t.penup()
t.setheading(180)
t.forward(500)
t.setheading(270)
t.forward(150)
t.left(90)
t.right(240)
t.goto(-100,150)
t.pendown()
t.fillcolor("hotpink")
t.begin_fill()
t.pencolor("crimson")
t.circle(30,180)
t.forward(42)
t.penup()
t.goto(-100,150)
t.left(70)
t.pendown()
t.circle(-30,180)
t.forward(42)
t.end_fill()


t.penup()
t.setheading(180)
t.forward(500)
t.setheading(270)
t.forward(150)
t.left(90)
t.right(240)
t.goto(-100,150)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
t.pencolor("crimson")
t.circle(20,180)
t.forward(28)
t.penup()
t.goto(-100,150)
t.left(70)
t.pendown()
t.circle(-20,180)
t.forward(28)
t.end_fill()

t.penup()
t.setheading(270)
t.goto(-18,300)
t.right(30)
t.pencolor("fuchsia")
t.pendown()
t.forward(370)
t.right(120)
start_pos=t.position()
start_heading=t.heading()
t.fillcolor("fuchsia")
t.begin_fill()
t.circle(30,180)
t.forward(34.6)
t.penup()
t.goto(start_pos)
t.setheading(start_heading)
t.pendown()
t.right(120)
t.circle(-30,180)
t.forward(34.6)
t.end_fill()

t.penup()
t.pencolor("white")
t.right(180)
t.forward(490)
t.setheading(270)
t.forward(100)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(70)
t.end_fill()
t.penup()
t.left(220)
t.setheading(0)
t.forward(200)
t.setheading(90)
t.forward(150)
t.setheading(180)
t.forward(130)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(40)
t.end_fill()

t.pencolor("black")
t.penup()
t.forward(20)
t.left(100)
t.forward(20)
t.pendown()
t.circle(2)
t.penup()
t.left(70)
t.forward(30)
t.pendown()
t.circle(2)
t.setheading(270)
t.penup()
t.forward(35)
t.setheading(180)
t.pendown()
t.forward(28)
t.penup()
t.left(150)
t.forward(70)
t.pencolor("white")
t.pendown()
t.forward(70)
t.penup()
t.setheading(90)
t.forward(70)
t.setheading(180)
t.forward(140)
t.left(49)
t.pendown()
t.forward(87)
t.penup()
t.setheading(90)
t.forward(145)
t.setheading(90)
t.forward(35)
t.right(150)
t.setheading(0)
t.forward(70)
t.left(110)
t.right(60)
t.pendown()
t.pencolor("gold")
t.fillcolor("gold")
t.begin_fill()
t.forward(30)
for i in range(4):
    t.right(145)
    t.forward(30)
    t.left(75)
    t.forward(30)
t.right(145)
t.forward(31)
t.end_fill()

for i in range(100):
    x=random.randint(-500,400)
    y=random.randint(-500,410)
    snow=turtle.Turtle()
    colors=["peachpuff","snow","aliceblue","lightpink","mistyrose","lightsteelblue","lemonchiffon","lightcoral"]
    snow.penup()
    snow.setheading(90)
    snow.goto(x,y)
    snow.pendown()
    snow.dot(random.randint(11,18))
    snow.dot(10,colors[i%len(colors)])
    
    
