'''學校公告展示系統'''
import tkinter as tk
school=tk.Tk()
school.title('學校公告展示系統')
label=tk.Label(text='校園公告',font=('新細明體',38),fg="#74FA36")
label2=tk.Label(text='--------------------------------------------------------------')
label3=tk.Label(text='返校打掃時間',font=('新細明體',24),fg="#070a16")
label5=tk.Label(text='日期: 7月17日',font=('新細明體',24),fg='black')
label4=tk.Label(text='原因: 打掃被扣太多分',font=('新細明體,24'),fg='black')
label.pack()
label2.pack()
label3.pack()
label5.pack()
label4.pack()
school.mainloop()